### PR TITLE
[art:build-info] feature: Add --add-cached-nodes flag to allow recollection of non-built packages

### LINKED ISSUE #100: [question] Use art:build-info for consumer of conan packages
I'm not sure if this is even possible with the Artifactory extension. I have project that is acting just as a consumer of conan packages but does not create a conan package itself. I'm only using `conan install .` for getting the dependencies.

I tried to follow the steps in https://github.com/conan-io/conan-extensions/blob/main/extensions/commands/art/README.md, however I only got to step 2a in the description. After `conan install` I have a JSON file that looks fine but I cannot `conan upload` because my consumer is not a conan package itself. `conan art:build-info create` then doesn't generate anything useful, just an almost empty JSON struct:

```json
{
    "version": "1.0.1",
    "name": "application-name",
    "number": "129",
    "agent": {},
    "started": "2024-01-04T10:24:14.908+0100",
    "buildAgent": {
        "name": "conan",
        "version": "2.0.16"
    },
    "modules": []
}
```

Nevertheless, I'd like to store the dependencies in the build info. My conan packages are stored on the same Artifactory (if that's a requirement) but just having the names for now would also be fine.

Is what I want even possible?

### PR DESCRIPTION
**Pull request by danimtb**
based on the work done at #78 but dropping the python requires related changes from #75

closes #78
closes #100 
closes #124

### CODE REVIEW

**Comment by danwalshnitro** [comment]
Hi @danimtb, this looks great. Can you please merge in the main branch? I need https://github.com/conan-io/conan-extensions/commit/2902e608821ddecd1d9980615225dd82bf945fb6 to be able to test this.

**Comment by danimtb** [comment]
@danwalshnitro ups, sorry for that. It's done now. Thanks for the quick response!

**Comment by danimtb** [comment]
@danwalshnitro did you have the time to try the changes? 😄

**Comment by danwalshnitro** [comment]
@danimtb Yeah, this PR works perfectly for our use-case so I've closed my PR. Thanks!

**Review by czoido — APPROVED** [review]

**Pull request merged**
