### PR TITLE
upgrade-qt-recipe: don't use xml.etree

### PR DESCRIPTION
**Pull request by ericLemanissier**
fixes https://github.com/conan-io/conan-extensions/issues/104

### CODE REVIEW

**Review by memsharded — APPROVED** [review]
Looks good, though it seems some CI is not passing.

**Comment by memsharded** [comment]
The CI failure seems unrelated to this PR, but to our server no longer available

**Comment by czoido** [comment]
I think https://github.com/conan-io/conan-extensions/pull/107 should fix the ci

**Comment by memsharded** [comment]
Thanks!!

**Pull request merged**
