### PR TITLE
upgrade qt: compute SHA if not available

### PR DESCRIPTION
**Pull request by ericLemanissier**
tested on qt 6.5.3

### CODE REVIEW

**Comment by danimtb** [comment]
Hi @ericLemanissier, thanks for the PR. This is needed when there are no hashes in the meta4 files right? Is this the case in qt 6.5.3?

**Comment by ericLemanissier** [comment]
yes, this is the case for few hours after a release.
Yesterday:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<metalink xmlns="urn:ietf:params:xml:ns:metalink">
  <generator>MirrorBrain/2.19.0</generator>
  <origin dynamic="true">https://download.qt.io/official_releases/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz.meta4</origin>
  <published>2023-09-28T12:09:01Z</published>
  <publisher>
    <name>Qt Project</name>
    <url>https://download.qt.io</url>
  </publisher>

  <file name="qt-everywhere-src-6.5.3.tar.xz">
    <size>798402796</size>

    <!-- <mtime>1695875164</mtime> -->



    <!-- Found 2 mirrors: 0 in the same network prefix, 0 in the same autonomous system,
         0 handling this country, 1 in the same region, 1 elsewhere -->

    <!-- Mirrors in the same network (90.127.0.0/16): -->

    <!-- Mirrors in the same AS (3215): -->

    <!-- Mirrors which handle this country (FR): -->

    <!-- Mirrors in the same continent (EU): -->
    <url location="de" priority="1">https://ftp.fau.de/qtproject/archive/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz</url>

    <!-- Mirrors in the rest of the world: -->
    <url location="ke" priority="2">https://qtproject.mirror.liquidtelecom.com/archive/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz</url>
  </file>
</metalink>
```

Today:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<metalink xmlns="urn:ietf:params:xml:ns:metalink">
  <generator>MirrorBrain/2.19.0</generator>
  <origin dynamic="true">https://download.qt.io/official_releases/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz.meta4</origin>
  <published>2023-09-29T10:52:28Z</published>
  <publisher>
    <name>Qt Project</name>
    <url>https://download.qt.io</url>
  </publisher>

  <file name="qt-everywhere-src-6.5.3.tar.xz">
    <size>798402796</size>

    <!-- <mtime>1695875164</mtime> -->

    <!-- internal id: 1028268 -->
    <hash type="md5">755db0527410df135609b51defa1a689</hash>
    <hash type="sha-1">342a166d84e6270b07f1d7b36728eefd8c0ddb71</hash>
    <hash type="sha-256">7cda4d119aad27a3887329cfc285f2aba5da85601212bcb0aea27bd6b7b544cb</hash>
    <pieces length="262144" type="sha-1">
      <hash>d68455cb0d7ffd106b17cd51dc30d6013e93ff1c</hash>
      <hash>1c5bbb3cfcd76e898a23ccbed2b02dc7f93da002</hash>
      <hash>dc174b68e3cf1bf2f1de814a4b22aaf22006755a</hash>
      <hash>387a66bd1238c66056a3762ca188c5a56a6488ad</hash>
      ...
    </pieces>


    <!-- Found 19 mirrors: 0 in the same network prefix, 0 in the same autonomous system,
         0 handling this country, 10 in the same region, 8 elsewhere -->

    <!-- Mirrors in the same network (90.127.0.0/16): -->

    <!-- Mirrors in the same AS (3215): -->

    <!-- Mirrors which handle this country (FR): -->

    <!-- Mirrors in the same continent (EU): -->
    <url location="gb" priority="1">https://mirrors.20i.com/pub/qt.io/archive/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz</url>
    <url location="nl" priority="2">https://ftp.nluug.nl/languages/qt/archive/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz</url>
    <url location="de" priority="3">https://mirror.netcologne.de/qtproject/archive/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz</url>
    <url location="gb" priority="4">https://mirrors.ukfast.co.uk/sites/qt.io/archive/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz</url>
    <url location="de" priority="5">https://qt-mirror.dannhauer.de/archive/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz</url>
    <url location="de" priority="6">https://ftp.fau.de/qtproject/archive/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz</url>
    <url location="dk" priority="7">https://mirrors.dotsrc.org/qtproject/archive/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz</url>
    <url location="pl" priority="8">https://ftp.icm.edu.pl/packages/qt/archive/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz</url>
    <url location="se" priority="9">https://ftp.acc.umu.se/mirror/qt.io/qtproject/archive/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz</url>
    <url location="fi" priority="10">https://www.nic.funet.fi/pub/mirrors/download.qt-project.org/archive/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz</url>

    <!-- Mirrors in the rest of the world: -->
    <url location="ng" priority="11">https://mirror.web4africa.ng/qt/archive/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz</url>
    <url location="ke" priority="12">https://qtproject.mirror.liquidtelecom.com/archive/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz</url>
    <url location="us" priority="13">https://qt.mirror.constant.com/archive/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz</url>
    <url location="sg" priority="14">https://mirrors.cloud.tencent.com/qt/archive/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz</url>
    <url location="cn" priority="15">https://mirrors.ustc.edu.cn/qtproject/archive/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz</url>
    <url location="cn" priority="16">https://mirrors.sjtug.sjtu.edu.cn/qt/archive/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz</url>
    <url location="jp" priority="17">https://ftp.jaist.ac.jp/pub/qtproject/archive/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz</url>
    <url location="jp" priority="18">https://ftp.yz.yamagata-u.ac.jp/pub/qtproject/archive/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz</url>
  </file>
</metalink>
```

**Comment by danimtb** [comment]
Thanks for the report.
So, it is not needed anymore?

**Comment by ericLemanissier** [comment]
@danimtb do you see a problem with this change ?

**Comment by ericLemanissier** [comment]
WDYT @memsharded @RubenRBS @czoido ?

**Comment by ericLemanissier** [comment]
@RubenRBS friendly ping

**Review by RubenRBS — APPROVED** [review]
Thanks a lot! :)

**Comment by RubenRBS** [comment]
Thanks @danimtb for pushing this along the finish line :)

**Pull request merged**
